from pathlib import Path
import re
p = Path('/home/ubuntu/one-king-one-crown-online/client/src/pages/Home.tsx')
s = p.read_text()
new = '''function Lobby({ room, onStart, loading, onKick, onLeave }: { room: RoomSnapshot; onStart: () => void; loading: boolean; onKick: (targetPlayerId: string) => void; onLeave: () => void }) { const count = room.state.players.length; return <main className="lobby"><header className="court-header"><a href="/" className="brand"><span className="brand-crown"><Crown size={20} /></span><span>ONE KING<br /><b>ONE CROWN</b></span></a><span className="phase-pill">WARTESAAL</span></header><section className="lobby-card"><p className="eyebrow">DEIN HOF IST BEREIT</p><h1>Versammle die Adligen.</h1><p className="lobby-lede">Teile diesen Raumcode mit deinen Mitspielenden. Sobald mindestens vier Personen am Tisch sitzen, kann der Host starten.</p><div className="lobby-code"><span>{room.code}</span><button onClick={() => navigator.clipboard.writeText(room.code)}><Copy size={18} /> Kopieren</button></div><div className="invite-tip">Einladung: Öffnet diese Website → <b>„Hof betreten“</b> → Code <b>{room.code}</b> eingeben.</div><div className="seats">{Array.from({ length: 8 }, (_, i) => { const noble = room.state.players[i]; return <div className={cn("seat-card", noble && "seat-filled")} key={i}>{noble ? <><div className="seat-medallion">{i + 1}</div><b>{noble.name}</b><span>{noble.id === room.viewer?.id ? "Du" : "Bereit"}</span>{room.viewer?.isHost && noble.id !== room.viewer.id && <button className="kick-button" disabled={loading} onClick={() => { if (window.confirm(`${noble.name} wirklich aus dem Raum entfernen?`)) onKick(noble.id); }}><UserX size={13} /> Entfernen</button>}</> : <><div className="seat-medallion">+</div><b>Freier Sitz</b><span>Einladung offen</span></>}</div>; })}</div>{room.viewer?.isHost ? <div className="lobby-actions"><Button className="primary-button" onClick={onStart} disabled={loading || count < 4}>{loading && <Loader2 className="animate-spin" />} {count < 4 ? `Noch ${4 - count} Person(en) nötig` : "Spiel beginnen"} <Crown size={17} /></Button><p>Beim Start erhält der König 1.000 Gold und acht Königskarten. Alle Adligen beginnen mit 600 Gold und acht Adligenkarten.</p></div> : <div className="waiting-host"><Loader2 className="animate-spin" /><b>Du sitzt am Hof.</b> Warte, bis {room.state.players.find(p => p.id === room.hostPlayerId)?.name ?? "der Host"} das Spiel startet.</div>}<button className="leave-link" onClick={onLeave}>Raum verlassen</button></section></main>; }'''
pattern = r'function Lobby\(.*?\n'
match = re.search(pattern, s)
if not match:
    raise SystemExit('Lobby function not found')
start = match.start()
# Lobby is the final function in this file, so replace through EOF.
p.write_text(s[:start] + new + '\n')
print('updated lobby')
